version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: attendance_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: attendance_monitoring
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - attendance_network

  app:
    build: .
    container_name: attendance_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      MONGO_URI: mongodb://admin:password123@mongodb:27017/attendance_monitoring?authSource=admin
      SESSION_TIMEOUT_HOURS: 12
      HEARTBEAT_MINUTES: 5
      AUTO_LOGOUT_CHECK_MINUTES: 5
    depends_on:
      - mongodb
    networks:
      - attendance_network

volumes:
  mongodb_data:

networks:
  attendance_network:
    driver: bridge