name: Trigger Auto-Logout (fallback)

on:
  schedule:
    # GitHub Actions cron doesn't support fractional hours; approximate 1.5 hour interval
    # by scheduling at 00:00, 01:30, 03:00, 04:30, ...
    - cron: '0 0 * * *'
    - cron: '30 1 * * *'
    - cron: '0 3 * * *'
    - cron: '30 4 * * *'
    - cron: '0 6 * * *'
    - cron: '30 7 * * *'
    - cron: '0 9 * * *'
    - cron: '30 10 * * *'
    - cron: '0 12 * * *'
    - cron: '30 13 * * *'
    - cron: '0 15 * * *'
    - cron: '30 16 * * *'
    - cron: '0 18 * * *'
    - cron: '30 19 * * *'
    - cron: '0 21 * * *'
    - cron: '30 22 * * *'
  workflow_dispatch: {}

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger internal cron endpoint
        env:
          DEPLOYMENT_URL: ${{ secrets.DEPLOYMENT_URL }}
          CRON_SECRET: ${{ secrets.CRON_SECRET }}
        run: |
          if [ -z "$DEPLOYMENT_URL" ] || [ -z "$CRON_SECRET" ]; then
            echo "ERROR: DEPLOYMENT_URL and CRON_SECRET must be set as repository secrets.";
            exit 1;
          fi

          echo "Calling $DEPLOYMENT_URL/internal/cron/auto-logout"
          STATUS_CODE=$(curl -s -o /tmp/cron_response.json -w "%{http_code}" -X POST "$DEPLOYMENT_URL/internal/cron/auto-logout" -H "Authorization: Bearer $CRON_SECRET")
          cat /tmp/cron_response.json || true
          echo "Status: $STATUS_CODE"
          if [ "$STATUS_CODE" -ge 400 ]; then
            echo "Cron call failed with status $STATUS_CODE";
            exit 1;
          fi
